<?php
/**
 * Created by PhpStorm.
 * User: alex
 * Date: 17-6-25
 * Time: 下午12:25
 */

namespace common\models;

use common\components\Common;
use yii;
use yii\base\Model;
use common\models\service\ApiBaseService;

class Api extends Model{

    public $queryParam;
    public $apiName;
    public $userId;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run(){
        $ApiBase = new ApiBaseService();
        $this->queryParam['isDefault'] = 2;
        $apiInfo = $ApiBase->getApi($this->queryParam);

        $param['url']    = $apiInfo['url'].$apiInfo['url_path'];
        $param['method'] = $apiInfo['request_method'];

        $this->apiName = $apiInfo['api_name'];

        if ($apiInfo['api_name']=='Robot')
        {
            $param['header'] = ["Authorization:APPCODE ".yii::$app->params['aliyun']['AppCode']];
        }elseif ($apiInfo['api_name']=='Turing')
        {
            $param['header'] = ["content-type: application/x-www-form-urlencoded"];
            $param['query_string']['key']    = yii::$app->params['turing']['APIkey'];
            $param['query_string']['userid'] = $this->userId;
        }
        $param['query_string'][$apiInfo['query_string']] = $this->queryParam['queryString'];

        return $this->invokeApi($param);
    }

    /**
     * invoke api to get infomations
     *
     * @param  array  $param['query_string'] -> array
     * @return string
     */
    public function invokeApi($param)
    {
        $content = Common::httpRequest($param['url'],$param['query_string'],$param['method'],$param['header']);
        return json_decode($content);
    }
}