<?php
namespace wechat\controllers;

use yii;
use yii\base\Controller;
use common\models\Api;
use wechat\models\Wechat;

/**
 * Index controller
 */
class IndexController extends Controller
{
    public $api;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->api = new Api();
        $this->api->queryParam['queryString'] = yii::$app->request->get('query_string');
    }

    public function actionIndex(){
        $wechat = new Wechat();

        if($wechat->getMsg()){
            echo $wechat->sendMsg();
        }
    }

    public function actionTest(){
        $wechat = new Wechat();
        var_dump($wechat->getAccessToken());

        var_dump($this->api->run());
    }

}
